-- KwikTip: English (US) locale — source of truth
-- The metatable returns the key itself for any untranslated string,
-- so this file needs no explicit string definitions.
-- Other locale files (generated by the CurseForge packager) override only
-- the keys that differ from English.
local ADDON_NAME, KwikTip = ...
KwikTip.L = setmetatable({}, { __index = function(_, k) return k end })
